# Generated by Django 3.0.3 on 2020-02-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamazon', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='mamazon.Product'),
        ),
    ]
